from mathutils import Vector

metahuman_mappings = {
    "base_pose:": ["base"],
    "C_glabella_down_pose": ["browDownL", "browDownR", "browLateralL", "browLateralR"],
    "C_glabella_up_pose": ["browRaiseInL", "browRaiseInR"],
    "C_nose_wrinkler_pose": ["noseWrinkleL", "noseWrinkleR"],
    "eye_convergence_pose": ["eyeLookLeftR", "eyeLookRightL"],
    "jaw_back_pose": ["jawBack"],
    "jaw_forward_pose": ["jawFwd"],
    "jaw_left_pose": ["jawLeft"],
    "jaw_open_pose": ["jawOpen"],
    "jaw_right_pose": ["jawRight"],
    "jaw_up_pose": ["jawChinRaiseDL", "jawChinRaiseDR"],
    "L_blink_pose": ["eyeBlinkL"],
    "L_brow_down_pose": ["browDownL"],
    "L_brow_squeeze_in_pose": ["browLateralL"],
    "L_brow_up_pose": ["browRaiseInL", "browRaiseOuterL"],
    "L_cheek_up_pose": [],
    "L_frown_pose": [],
    "L_lip_corner_narrow_pose": ["mouthCornerNarrowL"],
    "L_lip_corner_wide_pose": ["mouthCornerWideL"],
    "L_lower_lip_down_pose": ["mouthLowerLipDepressL"],
    "L_lower_lip_up_pose": ["jawChinRaiseDL"],
    "L_smile_pose": ["mouthCornerPullL"],
    "L_squeeze_pose": ["eyeCheekRaiseL"],
    "L_squint_inner_pose": ["eyeSquintInnerL"],
    "L_upper_lip_lower_pose": [],
    "L_upper_lip_raiser_pose": ["jawChinRaiseUL"],
    "L_upperLidDown_pose": [],
    "L_wide_pose": ["eyeWidenL"],
    "look_down_pose": ["eyeLookDownR", "eyeLookDownL"],
    "look_left_pose": ["eyeLookLeftR", "eyeLookLeftL"],
    "look_right_pose": ["eyeLookRightR", "eyeLookRightL"],
    "look_up_pose": ["eyeLookUpR", "eyeLookUpL"],
    "mouth_down_pose": ["mouthDown"],
    "mouth_up_pose": ["mouthUp"],
    "phoneme_ch_pose": [],
    "phoneme_fv_pose": ["mouthLowerLipBiteL", "mouthLowerLipBiteR"],
    "phoneme_mbp_pose": [],
    "phoneme_oo_pose": [],
    "R_blink_pose": ["eyeBlinkR"],
    "R_brow_down_pose": ["browDownR"],
    "R_brow_squeeze_in_pose": ["browLateralR"],
    "R_brow_up_pose": ["browRaiseInR", "browRaiseOuterR"],
    "R_cheek_up_pose": [],
    "R_frown_pose": [],
    "R_lip_corner_narrow_pose": ["mouthCornerNarrowR"],
    "R_lip_corner_wide_pose": ["mouthCornerWideR"],
    "R_lower_lip_down_pose": [],
    "R_lower_lip_up_pose": ["jawChinRaiseDR"],
    "R_smile_pose": ["mouthCornerPullR"],
    "R_squeeze_pose": ["eyeCheekRaiseR"],
    "R_squint_inner_pose": ["eyeSquintInnerR"],
    "R_upper_lip_lower_pose": [],
    "R_upper_lip_raiser_pose": ["jawChinRaiseUR"],
    "R_upperLidDown_pose": [],
    "R_wide_pose": ["eyeWidenR"],
    "tongue_back_pose": ["tongueIn"],
    "tongue_down_pose": ["tongueDown"],
    "tongue_forward_pose": ["tongueOut"],
    "tongue_up_pose": ["tongueUp"],
}

allowed_reorient_children = {
    "pelvis": ["spine_01"],
    "spine_01": ["spine_02"],
    "spine_02": ["spine_03"],
    "spine_03": ["spine_04"],
    "spine_04": ["spine_05"],
    "spine_05": ["neck_01"],
    "neck_01": ["neck_02"],
    "neck_02": ["head"],
    "thigh_r": ["calf_r"],
    "calf_r": ["foot_r"],
    "foot_r": ["ball_r"],
    "thigh_l": ["calf_l"],
    "calf_l": ["foot_l"],
    "foot_l": ["ball_l"],
}

base_bones = [
    "upperarm_r",
    "lowerarm_r",
    "hand_r",

    "upperarm_l",
    "lowerarm_l",
    "hand_l",

    "thigh_r",
    "calf_r",
    "foot_r",

    "thigh_l",
    "calf_l",
    "foot_l",

    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",

    "index_metacarpal_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",

    "middle_metacarpal_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",

    "ring_metacarpal_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",

    "pinky_metacarpal_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",

    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",

    "index_metacarpal_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",

    "middle_metacarpal_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",

    "ring_metacarpal_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",

    "pinky_metacarpal_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
]

hide_bones = [
    "ik_foot_roll_inner_r",
    "ik_foot_roll_outer_r",
    "ik_foot_roll_front_r",
    "ik_foot_roll_back_r",
    "ik_foot_target_r",
    "ik_foot_rot_ctrl_r",
    "ik_ball_roll_r",
    "ik_ball_ctrl_r"
    "ik_dog_ball_r",
    "ik_wolf_ball_r",

    "ik_foot_roll_inner_l",
    "ik_foot_roll_outer_l",
    "ik_foot_roll_front_l",
    "ik_foot_roll_back_l",
    "ik_foot_target_l",
    "ik_foot_rot_ctrl_l",
    "ik_ball_roll_l",
    "ik_ball_ctrl_l"
    "ik_dog_ball_l",
    "ik_wolf_ball_l",

    "ik_hand_parent_r",
    "ik_hand_parent_l",
]

# new name, target name, parent name
dupe_bones = [
    ("ik_hand_parent_r", "hand_r", "ik_hand_r"),
    ("ik_hand_parent_l", "hand_l", "ik_hand_l"),
    ("ik_hand_target_r", "hand_r", "ik_hand_parent_r"),
    ("ik_hand_target_l", "hand_l", "ik_hand_parent_l"),

    ("ik_finger_pole_thumb_r", "thumb_02_r", "ik_hand_target_r"),
    ("ik_finger_pole_index_r", "index_02_r", "ik_hand_target_r"),
    ("ik_finger_pole_middle_r", "middle_02_r", "ik_hand_target_r"),
    ("ik_finger_pole_ring_r", "ring_02_r", "ik_hand_target_r"),
    ("ik_finger_pole_pinky_r", "pinky_02_r", "ik_hand_target_r"),

    ("ik_finger_pole_thumb_l", "thumb_02_l", "ik_hand_target_l"),
    ("ik_finger_pole_index_l", "index_02_l", "ik_hand_target_l"),
    ("ik_finger_pole_middle_l", "middle_02_l", "ik_hand_target_l"),
    ("ik_finger_pole_ring_l", "ring_02_l", "ik_hand_target_l"),
    ("ik_finger_pole_pinky_l", "pinky_02_l", "ik_hand_target_l"),

    ("thumb_control_r", "thumb_02_r", "thumb_01_r"),
    ("index_control_r", "index_01_r", "index_metacarpal_r"),
    ("middle_control_r", "middle_01_r", "middle_metacarpal_r"),
    ("ring_control_r", "ring_01_r", "ring_metacarpal_r"),
    ("pinky_control_r", "pinky_01_r", "pinky_metacarpal_r"),

    ("thumb_control_l", "thumb_02_l", "thumb_01_l"),
    ("index_control_l", "index_01_l", "index_metacarpal_l"),
    ("middle_control_l", "middle_01_l", "middle_metacarpal_l"),
    ("ring_control_l", "ring_01_l", "ring_metacarpal_l"),
    ("pinky_control_l", "pinky_01_l", "pinky_metacarpal_l"),
]

parent_adjustment_bones = [
    ("L_eye_lid_lower_mid", "faceAttach"),
    ("L_eye_lid_upper_mid", "faceAttach"),
    ("R_eye_lid_lower_mid", "faceAttach"),
    ("R_eye_lid_upper_mid", "faceAttach"),
    ("eye_control_r", "eye_control_parent"),
    ("eye_control_l", "eye_control_parent"),
    ("R_Pupil_A_jnt", "R_Iris_A_jnt"),
    ("R_Iris_A_jnt", "R_Eyeball_A_jnt"),
    ("L_Pupil_A_jnt", "L_Iris_A_jnt"),
    ("L_Iris_A_jnt", "L_Eyeball_A_jnt"),
]

transform_adjustment_bones = [
    ("ik_finger_pole_thumb_r", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_index_r", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_middle_r", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_ring_r", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_pinky_r", Vector((0.05, 0.0, 0.0))),

    ("ik_finger_pole_thumb_l", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_index_l", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_middle_l", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_ring_l", Vector((0.05, 0.0, 0.0))),
    ("ik_finger_pole_pinky_l", Vector((0.05, 0.0, 0.0))),

    ("thumb_control_r", Vector((0.025, 0.0, 0.0))),
    ("index_control_r", Vector((0.025, 0.0, 0.0))),
    ("middle_control_r", Vector((0.025, 0.0, 0.0))),
    ("ring_control_r", Vector((0.025, 0.0, 0.0))),
    ("pinky_control_r", Vector((0.025, 0.0, 0.0))),

    ("thumb_control_l", Vector((0.025, 0.0, 0.0))),
    ("index_control_l", Vector((0.025, 0.0, 0.0))),
    ("middle_control_l", Vector((0.025, 0.0, 0.0))),
    ("ring_control_l", Vector((0.025, 0.0, 0.0))),
    ("pinky_control_l", Vector((0.025, 0.0, 0.0))),
]

# bone name, target name, space, weight
copy_location_bones = [
    ("ik_hand_parent_r", "ik_hand_r", "POSE", 1.0),
    ("ik_hand_parent_l", "ik_hand_l", "POSE", 1.0),
    ("ik_foot_rot_ctrl_r", "ik_foot_r", "POSE", 1.0),
    ("ik_foot_rot_ctrl_l", "ik_foot_l", "POSE", 1.0),
]

damped_track_bones = [
    ("R_eye", "eye_control_r"),
    ("L_eye", "eye_control_l"),
    ("FACIAL_R_Eye", "eye_control_r"),
    ("FACIAL_L_Eye", "eye_control_l"),
    ("R_Eyeball_A_jnt", "eye_control_r"),
    ("L_Eyeball_A_jnt", "eye_control_l"),
]

face_parent_adjustment_bones = [
    ("FACIAL_L_EyesackUpper4", "FACIAL_L_EyesackUpper"),
    ("FACIAL_R_EyesackUpper4", "FACIAL_R_EyesackUpper"),
    
    ("FACIAL_C_Chin1", "FACIAL_C_Chin"),
    ("FACIAL_C_Chin2", "FACIAL_C_Chin"),
    ("FACIAL_C_Chin3", "FACIAL_C_Chin"),
    ("FACIAL_L_Chin1", "FACIAL_L_Chin2"),
    ("FACIAL_L_Chin3", "FACIAL_L_Chin2"),
    ("FACIAL_R_Chin1", "FACIAL_R_Chin2"),
    ("FACIAL_R_Chin3", "FACIAL_R_Chin2"),

    ("FACIAL_L_Sideburn2", "FACIAL_L_Sideburn4"),
    ("FACIAL_L_Sideburn3", "FACIAL_L_Sideburn4"),
    ("FACIAL_L_Sideburn5", "FACIAL_L_Sideburn4"),
    ("FACIAL_L_Sideburn6", "FACIAL_L_Sideburn4"),
    ("FACIAL_R_Sideburn2", "FACIAL_R_Sideburn4"),
    ("FACIAL_R_Sideburn3", "FACIAL_R_Sideburn4"),
    ("FACIAL_R_Sideburn5", "FACIAL_R_Sideburn4"),
    ("FACIAL_R_Sideburn6", "FACIAL_R_Sideburn4"),


    ("FACIAL_L_12IPV_NasolabialF1", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF2", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF3", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF4", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF5", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF6", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF7", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF8", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialF9", "FACIAL_L_NasolabialFurrow"),
    ("FACIAL_L_12IPV_NasolabialB13", "FACIAL_L_NasolabialFurrow"),

]

extra_face_bones = [
    "FACIAL_C_Forehead1",
    "FACIAL_C_Forehead2",
    "FACIAL_C_Forehead3",

    "FACIAL_L_Forehead1",
    "FACIAL_L_Forehead2",
    "FACIAL_L_Forehead3",
    "FACIAL_L_ForeheadInA1",
    "FACIAL_L_ForeheadInA2",
    "FACIAL_L_ForeheadInA3",
    "FACIAL_L_ForeheadInB1",
    "FACIAL_L_ForeheadInB2",
    "FACIAL_L_ForeheadMid1",
    "FACIAL_L_ForeheadMid2",
    "FACIAL_L_ForeheadOutA1",
    "FACIAL_L_ForeheadOutA2",
    "FACIAL_L_ForeheadOutB1",
    "FACIAL_L_ForeheadOutB2",
    "FACIAL_R_Forehead1",
    "FACIAL_R_Forehead2",
    "FACIAL_R_Forehead3",
    "FACIAL_R_ForeheadInA1",
    "FACIAL_R_ForeheadInA2",
    "FACIAL_R_ForeheadInA3",
    "FACIAL_R_ForeheadInB1",
    "FACIAL_R_ForeheadInB2",
    "FACIAL_R_ForeheadMid1",
    "FACIAL_R_ForeheadMid2",
    "FACIAL_R_ForeheadOutA1",
    "FACIAL_R_ForeheadOutA2",
    "FACIAL_R_ForeheadOutB1",
    "FACIAL_R_ForeheadOutB2",

    "FACIAL_L_EyeCornerInner1",
    "FACIAL_L_EyeCornerInner2",
    "FACIAL_L_EyeCornerOuter1",
    "FACIAL_L_EyeCornerOuter2",
    "FACIAL_L_EyelashesCornerOuter1",
    "FACIAL_L_EyelashesUpperA1",
    "FACIAL_L_EyelashesUpperA2",
    "FACIAL_L_EyelashesUpperA3",
    "FACIAL_L_EyelidLowerA1",
    "FACIAL_L_EyelidLowerA2",
    "FACIAL_L_EyelidLowerA3",
    "FACIAL_L_EyelidLowerB1",
    "FACIAL_L_EyelidLowerB2",
    "FACIAL_L_EyelidLowerB3",
    "FACIAL_L_EyelidUpperA1",
    "FACIAL_L_EyelidUpperA2",
    "FACIAL_L_EyelidUpperA3",
    "FACIAL_L_EyelidUpperB1",
    "FACIAL_L_EyelidUpperB2",
    "FACIAL_L_EyelidUpperB3",
    "FACIAL_L_EyelidUpperFurrow1",
    "FACIAL_L_EyelidUpperFurrow2",
    "FACIAL_L_EyelidUpperFurrow3",
    "FACIAL_L_EyesackLower1",
    "FACIAL_L_EyesackLower2",
    "FACIAL_L_EyesackUpper1",
    "FACIAL_L_EyesackUpper2",
    "FACIAL_L_EyesackUpper3",
    "FACIAL_L_EyesackUpper4",
    "FACIAL_R_EyeCornerInner1",
    "FACIAL_R_EyeCornerInner2",
    "FACIAL_R_EyeCornerOuter1",
    "FACIAL_R_EyeCornerOuter2",
    "FACIAL_R_EyelashesCornerOuter1",
    "FACIAL_R_EyelashesUpperA1",
    "FACIAL_R_EyelashesUpperA2",
    "FACIAL_R_EyelashesUpperA3",
    "FACIAL_R_EyelidLowerA1",
    "FACIAL_R_EyelidLowerA2",
    "FACIAL_R_EyelidLowerA3",
    "FACIAL_R_EyelidLowerB1",
    "FACIAL_R_EyelidLowerB2",
    "FACIAL_R_EyelidLowerB3",
    "FACIAL_R_EyelidUpperA1",
    "FACIAL_R_EyelidUpperA2",
    "FACIAL_R_EyelidUpperA3",
    "FACIAL_R_EyelidUpperB1",
    "FACIAL_R_EyelidUpperB2",
    "FACIAL_R_EyelidUpperB3",
    "FACIAL_R_EyelidUpperFurrow1",
    "FACIAL_R_EyelidUpperFurrow2",
    "FACIAL_R_EyelidUpperFurrow3",
    "FACIAL_R_EyesackLower1",
    "FACIAL_R_EyesackLower2",
    "FACIAL_R_EyesackUpper1",
    "FACIAL_R_EyesackUpper2",
    "FACIAL_R_EyesackUpper3",
    "FACIAL_R_EyesackUpper4",
    
    "FACIAL_L_CheekInner1",
    "FACIAL_L_CheekInner2",
    "FACIAL_L_CheekInner3",
    "FACIAL_L_CheekInner4",
    "FACIAL_L_CheekLower1",
    "FACIAL_L_CheekLower2",
    "FACIAL_L_CheekLower3",
    "FACIAL_L_CheekLower4",
    "FACIAL_L_CheekOuter1",
    "FACIAL_L_CheekOuter2",
    "FACIAL_L_CheekOuter3",
    "FACIAL_R_CheekInner1",
    "FACIAL_R_CheekInner2",
    "FACIAL_R_CheekInner3",
    "FACIAL_R_CheekInner4",
    "FACIAL_R_CheekLower1",
    "FACIAL_R_CheekLower2",
    "FACIAL_R_CheekLower3",
    "FACIAL_R_CheekLower4",
    "FACIAL_R_CheekOuter1",
    "FACIAL_R_CheekOuter2",
    "FACIAL_R_CheekOuter3",
    
    "FACIAL_C_LipUpper1",
    "FACIAL_C_LipUpper2",
    "FACIAL_C_LipUpper3",
    "FACIAL_C_LipLower1",
    "FACIAL_C_LipLower2",
    "FACIAL_C_LipLower3",
    
    "FACIAL_L_LipUpper1",
    "FACIAL_L_LipUpper2",
    "FACIAL_L_LipUpper3",
    "FACIAL_L_LipUpperOuter1",
    "FACIAL_L_LipUpperOuter2",
    "FACIAL_L_LipUpperOuter3",
    "FACIAL_L_LipCorner1",
    "FACIAL_L_LipCorner2",
    "FACIAL_L_LipCorner3",
    "FACIAL_L_LipLower1",
    "FACIAL_L_LipLower2",
    "FACIAL_L_LipLower3",
    "FACIAL_L_LipLowerOuter1",
    "FACIAL_L_LipLowerOuter2",
    "FACIAL_L_LipLowerOuter3",
    "FACIAL_R_LipUpper1",
    "FACIAL_R_LipUpper2",
    "FACIAL_R_LipUpper3",
    "FACIAL_R_LipUpperOuter1",
    "FACIAL_R_LipUpperOuter2",
    "FACIAL_R_LipUpperOuter3",
    "FACIAL_R_LipCorner1",
    "FACIAL_R_LipCorner2",
    "FACIAL_R_LipCorner3",
    "FACIAL_R_LipLower1",
    "FACIAL_R_LipLower2",
    "FACIAL_R_LipLower3",
    "FACIAL_R_LipLowerOuter1",
    "FACIAL_R_LipLowerOuter2",
    "FACIAL_R_LipLowerOuter3",
    
    "FACIAL_L_NostrilThickness1",
    "FACIAL_L_NostrilThickness2",
    "FACIAL_R_NostrilThickness1",
    "FACIAL_R_NostrilThickness2",
    
    "FACIAL_C_Chin1",
    "FACIAL_C_Chin2",
    "FACIAL_C_Chin3",
    "FACIAL_L_Chin1",
    "FACIAL_L_Chin3",
    "FACIAL_R_Chin1",
    "FACIAL_R_Chin3",
    "FACIAL_R_Chin3",

    "FACIAL_L_Sideburn2",
    "FACIAL_L_Sideburn3",
    "FACIAL_L_Sideburn5",
    "FACIAL_L_Sideburn6",
    "FACIAL_R_Sideburn2",
    "FACIAL_R_Sideburn3",
    "FACIAL_R_Sideburn5",
    "FACIAL_R_Sideburn6",
    
    "FACIAL_C_TongueUpper2",
    "FACIAL_C_TongueUpper3",
    "FACIAL_C_TongueLower3",
    "FACIAL_L_TongueSide2",
    "FACIAL_L_TongueSide3",
    "FACIAL_R_TongueSide2",
    "FACIAL_R_TongueSide3",
    
    "FACIAL_L_12IPV_NasolabialF1",
    "FACIAL_L_12IPV_NasolabialF2",
    "FACIAL_L_12IPV_NasolabialF3",
    "FACIAL_L_12IPV_NasolabialF4",
    "FACIAL_L_12IPV_NasolabialF5",
    "FACIAL_L_12IPV_NasolabialF6",
    "FACIAL_L_12IPV_NasolabialF7",
    "FACIAL_L_12IPV_NasolabialF8",
    "FACIAL_L_12IPV_NasolabialF9",
    "FACIAL_L_12IPV_NasolabialB1",
    "FACIAL_L_12IPV_NasolabialB2",
    "FACIAL_L_12IPV_NasolabialB3",
    "FACIAL_L_12IPV_NasolabialB4",
    "FACIAL_L_12IPV_NasolabialB5",
    "FACIAL_L_12IPV_NasolabialB6",
    "FACIAL_L_12IPV_NasolabialB7",
    "FACIAL_L_12IPV_NasolabialB8",
    "FACIAL_L_12IPV_NasolabialB9",
    "FACIAL_L_12IPV_NasolabialB10",
    "FACIAL_L_12IPV_NasolabialB11",
    "FACIAL_L_12IPV_NasolabialB12",
    "FACIAL_L_12IPV_NasolabialB13",
    "FACIAL_R_12IPV_NasolabialF1",
    "FACIAL_R_12IPV_NasolabialF2",
    "FACIAL_R_12IPV_NasolabialF3",
    "FACIAL_R_12IPV_NasolabialF4",
    "FACIAL_R_12IPV_NasolabialF5",
    "FACIAL_R_12IPV_NasolabialF6",
    "FACIAL_R_12IPV_NasolabialF7",
    "FACIAL_R_12IPV_NasolabialF8",
    "FACIAL_R_12IPV_NasolabialF9",
    "FACIAL_R_12IPV_NasolabialB1",
    "FACIAL_R_12IPV_NasolabialB2",
    "FACIAL_R_12IPV_NasolabialB3",
    "FACIAL_R_12IPV_NasolabialB4",
    "FACIAL_R_12IPV_NasolabialB5",
    "FACIAL_R_12IPV_NasolabialB6",
    "FACIAL_R_12IPV_NasolabialB7",
    "FACIAL_R_12IPV_NasolabialB8",
    "FACIAL_R_12IPV_NasolabialB9",
    "FACIAL_R_12IPV_NasolabialB10",
    "FACIAL_R_12IPV_NasolabialB11",
    "FACIAL_R_12IPV_NasolabialB12",
    "FACIAL_R_12IPV_NasolabialB13",
]